import Head from "next/head";
//import Link from "next/link";
import {  useUser } from "@clerk/nextjs";
import { useForm } from "react-hook-form";


import { api } from "~/utils/api";
import { NavBar } from "~/components/NavBar";

type SellItemForm = {
    name: String;
    description: string;
    price: number;
}

export default function SellAnItem() {
    const { register, handleSubmit, watch, formState: { errors } } = useForm<SellItemForm>();
    const onSubmit = (formData: SellItemForm) => console.log(formData);
  const user = useUser();


  return (
    <>
      <Head>
        <title>Sell An Item</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900 flex min-h-screen flex-col items-center justify-center bg-gray-800">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1>Sell An Item</h1>
     <form onSubmit={handleSubmit(onSubmit)}>
        
      <input {...register("name", { required: true})} />
       <input {...register("description", { required: true })} />
       <input type="number" step="0.01" {...register("price", { required: true })} />
            <input type="submit" />
    </form>
        </div>
      </main>
    </>
  );
}
